.github/workflows/release.yml, .zenodo.json, pyproject.toml
=> fix: add .zenodo.json for valid metadata crawling (contributors: @sasanjac)

.github/workflows/release.yml
=> build: CI token

examples/grids/HV_8_Bus_Set1_steadystate_case.json, examples/grids/HV_8_Bus_Set1_topology_case.json, examples/grids/HV_8_Bus_steadystate_case.json, examples/grids/HV_8_Bus_topology.json, examples/grids/HV_8_Bus_topology_case.json, powerfactory_utils/schema/base.py
=> feat: add schema version

pdm.lock, powerfactory_utils/exporter/exporter.py
=> fix: all setpoints in SI (#30)

powerfactory_utils/exporter/exporter.py, powerfactory_utils/powerfactory_types.py
=> fix: Coupler StationCubicle may be empty

powerfactory_utils/exporter/exporter.py
=> fix: switch transformer node assignment

.github/workflows/checks.yml, .github/workflows/release.yml, .github/workflows/tests.yml
=> build: update CI actions

powerfactory_utils/exporter/exporter.py
=> fix: consider number of units when creating steadystate_case for producer

.github/workflows/checks.yml, .github/workflows/release.yml, .github/workflows/tests.yml
=> build: update CI

powerfactory_utils/exporter/exporter.py
=> fix: optional parameters default to *, which raises Exceptions

examples/powerfactory_export.ipynb, powerfactory_utils/exporter/exporter.py, powerfactory_utils/schema/steadystate_case/case.py
=> feat: cross check if number of ssc entries match number of related entries in topology

.github/workflows/release.yml
=> fix: missed date in zenodo metadata file when bump version number

.github/workflows/release.yml, powerfactory_utils/schema/base.py
=> build:  create json schema for repository version

.github/workflows/release.yml
=> build: release on pypi

powerfactory_utils/exporter/exporter.py, powerfactory_utils/interface.py, powerfactory_utils/schema/steadystate_case/case.py
=> fix: wrong double prefix for generators in compound models

.github/workflows/checks.yml, .github/workflows/release.yml, .github/workflows/tests.yml, pdm.lock, powerfactory_utils/interface.py, powerfactory_utils/powerfactory_types.py, powerfactory_utils/schema/base.py, pyproject.toml
=> ci: update CI

.github/workflows/release.yml, README.md
=> docs: rewrite README to use package from pypi

pdm.lock, powerfactory_tools/exporter/exporter.py, powerfactory_tools/interface.py
=> fix: unit settings dir doesn't exist in default PF project

examples/grids/HV_8_Bus_Set1_steadystate_case.json, examples/grids/HV_8_Bus_Set1_topology_case.json, examples/grids/HV_8_Bus_steadystate_case.json, examples/grids/HV_8_Bus_topology.json, examples/grids/HV_8_Bus_topology_case.json, powerfactory_tools/exporter/exporter.py, powerfactory_tools/interface.py
=> feat: improve error handling and logging

pdm.lock, powerfactory_tools/exporter/exporter.py
=> fix: create proper producer name in steadystate case

powerfactory_tools/powerfactory_types.py
=> fix: add neutral to phase information

powerfactory_tools/schema/topology/load.py
=> fix: add neutral to schema phase information

.github/workflows/release.yml, .zenodo.json, CITATION.cff, pyproject.toml
=> fix: update citation file automatically

pdm.lock, powerfactory_tools/exporter/exporter.py, powerfactory_tools/exporter/load_power.py, pyproject.toml
=> fix: wrong sign for MV_Load Producer

.github/workflows/checks.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .gitignore, pdm.lock, powerfactory_tools/exporter/exporter.py, pyproject.toml
=> fix: adapt load controller to schema fix

.github/workflows/checks.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .gitignore, pdm.lock, powerfactory_tools/exporter/exporter.py, powerfactory_tools/powerfactory_types.py, pyproject.toml
=> feat: add neutral conductor information to exporter

examples/README.md
=> docs: add documentation for controller example

powerfactory_tools/exporter/exporter.py
=> fix: neutral line does not have conductance in every case

pdm.lock, pyproject.toml
=> fix: force use of pydantic < 2.0 before release 1.6

powerfactory_tools/constants.py, powerfactory_tools/exporter/exporter.py
=> fix: precise handling of floats

.github/workflows/checks.yml, .github/workflows/release.yml, .github/workflows/tests.yml, powerfactory_tools/exporter/exporter.py, powerfactory_tools/powerfactory_types.py
=> fix: vectorgroup 'YNyn5' is missing

powerfactory_tools/exporter/exporter.py
=> fix: check if assignment of power factor is correct

powerfactory_tools/exporter/exporter.py, powerfactory_tools/interface.py, powerfactory_tools/powerfactory_types.py
=> feat: extend PF types

powerfactory_tools/interface.py, powerfactory_tools/powerfactory_types.py
=> feat: add comfort functions for scenario and grid variants

examples/grids/Base/Base_HV_9_Bus_steadystate_case.json, examples/grids/Base/Base_HV_9_Bus_topology.json, examples/grids/Base/Base_HV_9_Bus_topology_case.json, examples/grids/Industry_Park/Industry_Park_HV_9_Bus_steadystate_case.json, examples/grids/Industry_Park/Industry_Park_HV_9_Bus_topology.json, examples/grids/Industry_Park/Industry_Park_HV_9_Bus_topology_case.json, examples/grids/Industry_Park/Industry_Park_MV_2_Bus_steadystate_case.json, examples/grids/Industry_Park/Industry_Park_MV_2_Bus_topology.json, examples/grids/Industry_Park/Industry_Park_MV_2_Bus_topology_case.json, examples/grids/Outage/Outage_HV_9_Bus_steadystate_case.json, examples/grids/Outage/Outage_HV_9_Bus_topology.json, examples/grids/Outage/Outage_HV_9_Bus_topology_case.json, pdm.lock, powerfactory_tools/exporter/exporter.py, powerfactory_tools/powerfactory_types.py, pyproject.toml
=> fix: lengths of lines always null

tests/test_schema.py
=> fix: make json export more efficient

powerfactory_tools/exporter/exporter.py
=> fix: use I-type load model for LV-Loads as default instead of Z-type

README.md
=> docs: precise remarks for export

examples/grids/Base/Base_HV_9_Bus_topology.json, examples/grids/Industry_Park/Industry_Park_HV_9_Bus_topology.json, examples/grids/Outage/Outage_HV_9_Bus_topology.json, powerfactory_tools/exporter/exporter.py
=> feat: mapping back the system_type to type for loads

powerfactory_tools/versions/pf2022/interface.py
=> fix: partly neglecting PR #232 after merge of PR #122

powerfactory_tools/versions/pf2022/constants.py, powerfactory_tools/versions/pf2022/exporter/exporter.py
=> fix: line length

.gitignore, CONTRIBUTING.md
=> docs: update README and link to organisation

src/powerfactory_tools/versions/pf2022/data.py, src/powerfactory_tools/versions/pf2022/interface.py, src/powerfactory_tools/versions/pf2022/types.py
=> feat: extend interface for current and voltage sources

examples/grids/3_Bus/3_Bus__HV_3_Bus__steadystate_case.json, examples/grids/3_Bus/3_Bus__HV_3_Bus__topology.json, examples/grids/3_Bus/3_Bus__HV_3_Bus__topology_case.json, examples/grids/Base/Base__HV_9_Bus__steadystate_case.json, examples/grids/Base/Base__HV_9_Bus__topology.json, examples/grids/Base/Base__HV_9_Bus__topology_case.json, examples/grids/Industry_Park/Industry_Park__HV_9_Bus__steadystate_case.json, examples/grids/Industry_Park/Industry_Park__HV_9_Bus__topology.json, examples/grids/Industry_Park/Industry_Park__HV_9_Bus__topology_case.json, examples/grids/Industry_Park/Industry_Park__MV_2_Bus__steadystate_case.json, examples/grids/Industry_Park/Industry_Park__MV_2_Bus__topology.json, examples/grids/Industry_Park/Industry_Park__MV_2_Bus__topology_case.json, examples/grids/Outage/Outage__HV_9_Bus__steadystate_case.json, examples/grids/Outage/Outage__HV_9_Bus__topology.json, examples/grids/Outage/Outage__HV_9_Bus__topology_case.json
=> fix: update example grids to PF 2024

src/powerfactory_tools/versions/pf2022/interface.py, src/powerfactory_tools/versions/pf2024/interface.py
=> fix: setup logging

src/powerfactory_tools/versions/pf2022/exporter/exporter.py, src/powerfactory_tools/versions/pf2022/exporter/load_power.py, src/powerfactory_tools/versions/pf2022/types.py, src/powerfactory_tools/versions/pf2024/exporter/exporter.py, src/powerfactory_tools/versions/pf2024/exporter/load_power.py, src/powerfactory_tools/versions/pf2024/types.py
=> fix: typing in exporter and load_power

src/powerfactory_tools/versions/pf2022/exporter/exporter.py, src/powerfactory_tools/versions/pf2024/exporter/exporter.py
=> fix: file name for exporter in pf2022
